DROP TABLE IF EXISTS practice CASCADE;
DROP TABLE IF EXISTS admin CASCADE;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS challenge CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS "statusPractice" CASCADE;
DROP TABLE IF EXISTS "statusChallenge" CASCADE;