// Code generated by sqlc. DO NOT EDIT.
// source: dashboard-profile.sql

package db

import (
	"context"
	"database/sql"
)

const homeDashboard = `-- name: HomeDashboard :one
SELECT
	m.username, m.nama_lengkap, m.url_foto, m.university,
	(SELECT COUNT(sp.id) FROM "statusPractice" sp left join mahasiswa m on (m.id = sp.id_mahasiswa) where sp.id_mahasiswa = $1 GROUP BY m.nama_lengkap) as finished_practice,
	(SELECT COUNT(id) as jumlah_practice FROM practice),
	(SELECT COUNT(sc.id) FROM "statusChallenge" sc left join mahasiswa m on (m.id = sc.id_mahasiswa) where sc.id_mahasiswa = $1 GROUP BY m.nama_lengkap) as finished_challange,
	(SELECT COUNT(id) as jumlah_challange FROM challenge),
	SUM((SELECT SUM(skor_practice) FROM "statusPractice" WHERE id_mahasiswa = $1) + (SELECT SUM(sc.skor_challenge) FROM "statusChallenge" sc  WHERE id_mahasiswa = $1)) as total_skor
FROM
	mahasiswa m
WHERE
	id = $1
GROUP BY m.id
`

type HomeDashboardRow struct {
	Username          string `json:"username"`
	NamaLengkap       sql.NullString `json:"nama_lengkap"`
	UrlFoto           sql.NullString `json:"url_foto"`
	University        sql.NullString `json:"university"`
	FinishedPractice  sql.NullInt64  `json:"finished_practice"`
	JumlahPractice    int64  `json:"jumlah_practice"`
	FinishedChallange sql.NullInt64  `json:"finished_challange"`
	JumlahChallange   int64  `json:"jumlah_challange"`
	TotalSkor         sql.NullInt64  `json:"total_skor"`
}

func (q *Queries) HomeDashboard(ctx context.Context, idMahasiswa int32) (HomeDashboardRow, error) {
	row := q.db.QueryRowContext(ctx, homeDashboard, idMahasiswa)
	var i HomeDashboardRow
	err := row.Scan(
		&i.Username,
		&i.NamaLengkap,
		&i.UrlFoto,
		&i.University,
		&i.FinishedPractice,
		&i.JumlahPractice,
		&i.FinishedChallange,
		&i.JumlahChallange,
		&i.TotalSkor,
	)
	return i, err
}
