// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID        int32          `json:"id"`
	Job       sql.NullString `json:"job"`
	Photo     sql.NullString `json:"photo"`
	Bio       sql.NullString `json:"bio"`
	Status    sql.NullString `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
}

type Category struct {
	ID           int32          `json:"id"`
	NameCategory sql.NullString `json:"name_category"`
	CreatedAt    time.Time      `json:"created_at"`
	FinishedAt   time.Time   `json:"finished_at"`
}

type Challenge struct {
	ID                int32          `json:"id"`
	Tema              sql.NullString `json:"tema"`
	JudulChallenge    sql.NullString `json:"judul_challenge"`
	Latar             sql.NullString `json:"latar"`
	UrlVideoChallenge sql.NullString `json:"url_video_challenge"`
	TaskChallenge     sql.NullString `json:"task_challenge"`
	UjianChallenge    sql.NullString `json:"ujian_challenge"`
	SkorChallenge     sql.NullString `json:"skor_challenge"`
	IDAdmin           sql.NullInt32  `json:"id_admin"`
	IDCategory        sql.NullInt32  `json:"id_category"`
	CreatedAt         time.Time      `json:"created_at"`
	FinishedAt        time.Time   `json:"finishedAt"`
}

type Event struct {
	ID             int32          `json:"id"`
	UrlFoto        sql.NullString `json:"url_foto"`
	JudulEvent     sql.NullString `json:"judul_event"`
	DeskripsiEvent sql.NullString `json:"deskripsi_event"`
	KriteriaEvent  sql.NullString `json:"kriteria_event"`
	TanggalEvent   sql.NullString `json:"tanggal_event"`
	IDMahasiswa    int32          `json:"id_mahasiswa"`
	IDAdmin        sql.NullInt32  `json:"id_admin"`
	CreatedAt      time.Time   `json:"created_at"`
	FinishedAt     time.Time   `json:"finished_at"`
}

type Mahasiswa struct {
	ID            int32     `json:"id"`
	Username      string    `json:"username"`
	Password      string    `json:"password"`
	NomorHp       string    `json:"nomor_hp"`
	Email         string    `json:"email"`
	UrlFoto       string    `json:"url_foto"`
	NamaLengkap   string    `json:"nama_lengkap"`
	TanggalLahir  string    `json:"tanggal_lahir"`
	JenisKelamin  string    `json:"jenis_kelamin"`
	University    string    `json:"university"`
	Nim           string    `json:"nim"`
	Jurusan       string    `json:"jurusan"`
	TahunMasuk    string    `json:"tahun_masuk"`
	KotaKabupaten string    `json:"kota_kabupaten"`
	Token         string    `json:"token"`
	CreatedAt     time.Time `json:"created_at"`
}

type Practice struct {
	ID                int32          `json:"id"`
	ThumbnailPractice sql.NullString `json:"thumbnail_practice"`
	JudulPractice     sql.NullString `json:"judul_practice"`
	Definisi          sql.NullString `json:"definisi"`
	Deskripsi         sql.NullString `json:"deskripsi"`
	UrlVideoPractice  sql.NullString `json:"url_video_practice"`
	TaskPractice      sql.NullString `json:"task_practice"`
	UjianPractice     sql.NullString `json:"ujian_practice"`
	IDAdmin           sql.NullInt32  `json:"id_admin"`
	IDCategory        int32          `json:"id_category"`
	CreatedAt         time.Time      `json:"created_at"`
	FinishedAt        time.Time   `json:"finished_at"`
}

type StatusChallenge struct {
	ID             int32         `json:"id"`
	SkorChallenge  sql.NullInt32 `json:"skor_challenge"`
	IDMahasiswa    int32         `json:"id_mahasiswa"`
	IDChallenge    sql.NullInt32 `json:"id_challenge"`
	CheckChallenge sql.NullInt32 `json:"check_challenge"`
	FinishedAt     time.Time  `json:"finishedAt"`
}

type StatusPractice struct {
	ID            int32         `json:"id"`
	SkorPractice  sql.NullInt32 `json:"skor_practice"`
	IDMahasiswa   int32         `json:"id_mahasiswa"`
	IDPractice    sql.NullInt32 `json:"id_practice"`
	CheckPractice sql.NullInt32 `json:"check_practice"`
	FinishedAt    time.Time  `json:"finishedAt"`
}
